@baseURL = http://localhost:3000/api



@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0QHRlc3QuZnIiLCJpYXQiOjE3Nzk4MTQ1NTQsImV4cCI6MTc3OTgxODE1NH0.A_LUV5-zY8PM3taMlpI_SAiQgAV4UkMRbGXbhiheqE0

POST {{baseURL}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.fr",
    "password": "Test1234"
}

### Recherche d'un élève avec son prénom
GET {{baseURL}}/eleves?prenom=Jean HTTP/1.1
Authorization: Bearer {{token}}

### Recherche d'un élève avec son nom
GET {{baseURL}}/eleves?nom=Dubois HTTP/1.1
Authorization: Bearer {{token}}


### Recherche d'un élève avec son nom et son prénom
GET {{baseURL}}/eleves?nom=Dubois&prenom=Marie HTTP/1.1
Authorization: Bearer {{token}}


### Historique de sanction d'un élève par son id

GET {{baseURL}}/eleves/5/sanctions HTTP/1.1
Authorization: Bearer {{token}}


### Historique de sanction d'un élève par son id le queryParameter from

GET {{baseURL}}/eleves/5/sanctions?from=01/01/2025 HTTP/1.1
Authorization: Bearer {{token}}

### Historique de sanction d'un élève par son id les queryParameter from et to

GET {{baseURL}}/eleves/5/sanctions?from=01/01/2025&to=31/12/2025 HTTP/1.1
Authorization: Bearer {{token}}

